Table product_variants {
  id uuid [pk]
  product_id uuid [ref: > products.id]
  name varchar(100) [not null, note: "Example: Small, Large, Hot, Ice"]
  sku varchar(100) [not null, unique]
  price decimal(15,2) [not null, default: 0]
  is_active boolean [not null, default: true]
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
  deleted_at timestamp

  indexes {
    product_id
    sku
    is_active
    deleted_at
  }

  Note: "Detail varian dan harga produk"
}
